# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

# [[main]]
#  name = "BIMpogovori"
#  url = "http://bimpogovori.si"
#  weight = 10
# 
# [[main]]
#  name = "mojFGG"
#  url = "https://buildingsmart.fgg.uni-lj.si"
#  weight = 20

[[main]]
name = "Predavanja"
pageRef = ""
weight = 10

[[main]]
name = "Obdelava podatkov"
parent = "Predavanja"
pageRef = "/posts/op_2023"
weight = 10

[[main]]
name = "Praktično usposabljanje"
parent = "Predavanja"
pageRef = "/posts/pu_2023"
weight = 20

[[main]]
name = "Programiranje"
parent = "Predavanja"
pageRef = "/posts/prog_2024"
weight = 30

[[main]]
name = "Computer Programming (ERASMUS)"
parent = "Predavanja"
pageRef = "/posts/cp_2024"
weight = 35

[[main]]
name = "Računalništvo in informatika"
parent = "Predavanja"
pageRef = "/posts/racinf_2023"
weight = 40

[[main]]
name = "Računalništvo"
parent = "Predavanja"
pageRef = "/posts/rac_2023"
weight = 50

[[main]]
name = "------"
parent = "Predavanja"
pageRef = ""
weight = 60

[[main]]
name = "Python za inženirje - video"
parent = "Predavanja"
pageRef = "/pzi-video"
weight = 70

[[main]]
name = "HTCondor za inženirje"
parent = "Predavanja"
pageRef = "/htcondor"
weight = 80

# 
# [[main]]
#  name = "BIM A+"
#  parent = "Lectures"
#  pageRef = "lectures/bimaplus"
#  weight = 20

# [[main]]
#  name = "Računalništvo"
#  parent = "Lectures"
#  pageRef = "lectures/rac"
#  weight = 30
# 
# [[main]]
#  name = "Računalništvo in informatika"
#  parent = "Lectures"
#  pageRef = "lectures/racinf"
#  weight = 40

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

[[subnavigation]]
 name = "BIMpogovori"
 url = "http://bimpogovori.si"
 pre = "link"
 weight = 10

[[subnavigation]]
 name = "mojFGG"
 url = "https://buildingsmart.fgg.uni-lj.si"
 pre = "link"
 weight = 20

[[subnavigation]]
 name = "Programiranje za inženirje"
 url = "https://pzi.si"
 pre = "link"
 weight = 30

# [[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20
# 
# [[main]]
# name = "Tags"
# pageRef = "tags"
# weight = 30

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
